### PR TITLE
feat: migrate to go-logr

### PR DESCRIPTION
**Pull request by odsod**
Standard interface for logging, which enables the library user to plug
in a logging implementation (Zap, standard library, etc).

### CODE REVIEW

**Comment by gust1n** [comment]
LGTM, I both like the logr interface, but also not being tied to a specific implementation. Especially for a library like this, I think it really makes sense to allow users to control the logging.

**Review by Edholm — APPROVED** [review]
image

**Comment by Edholm** [comment]
I was thinking that one could attach the logger to the context being fed to each service as well. Then those could make use of `logr.FromContextOrDiscard` (or whatever the method is called) _if_ they wanted to.

**Comment by odsod** [comment]
@Edholm Brilliant!! Let me experiment with this and propose a follow-up change

**Pull request merged**
